--Project 3

--Queries

--Carlos RIBADENEIRA 

--1
SELECT		ITEMID, DESCRIPTION, LISTPRICE
FROM		PET..MERCHANDISE
WHERE		LISTPRICE > (SELECT AVG(LISTPRICE) FROM PET..MERCHANDISE)

--2
SELECT		M.ITEMID, M.Description, AVG(COST) AS 'AVERAGE COST', AVG(SALEPRICE) AS 'AVERAGE SALE PRICE'
FROM		PET..ORDERITEM O JOIN PET..MERCHANDISE M ON O.ITEMID = M.ITEMID
			JOIN PET..SALEITEM S ON M.ITEMID = S.ITEMID 
GROUP BY	M.ITEMID, M.DESCRIPTION 
HAVING		AVG(SALEPRICE)>1.5*AVG(COST)

--3
SELECT		E.EMPLOYEEID, LASTNAME, SUM(QUANTITY * SALEPRICE) AS ' TOTALSALES', (SUM(QUANTITY * SALEPRICE) / (SELECT SUM(QUANTITY*SALEPRICE) FROM PET..SALEITEM)) *100 AS PCTSALES
FROM		PET..SALEITEM S JOIN PET..SALE SA ON S.SALEID = SA.SALEID
			JOIN PET..EMPLOYEE E ON SA.EMPLOYEEID = E.EMPLOYEEID
GROUP BY	E.EMPLOYEEID, LASTNAME
ORDER BY Sum([Quantity]*[SalePrice]) DESC;
--4---
SELECT		TOP 1 SU.SUPPLIERID, SU.NAME, AVG(SUM(M.SHIPPINGCOST)/(SELECT SUM(O.QUANTITY*O.COST) FROM PET..ORDERITEM O))*100
FROM		PET..SUPPLIER SU JOIN PET..MERCHANDISEORDER M ON SU.SUPPLIERID = M.SUPPLIERID
			JOIN PET..ORDERITEM O ON M.PONUMBER = O.PONUMBER 
GROUP BY	SU.SUPPLIERID, SU.NAME
ORDER BY	((AVG(SUM(M.SHIPPINGCOST)/(SELECT SUM(O.QUANTITY*O.COST) FROM PET..ORDERITEM O))*100))



--5

SELECT		TOP 1 C.CUSTOMERID, C.LASTNAME, C.FIRSTNAME, SUM(SI.SALEPRICE*SI.QUANTITY) MERCTOTAL, SUM(SA.SALEID) ANIMALTOTAL, SUM(SI.SALEPRICE*SI.QUANTITY)+SUM(SA.SALEID) GRANDTOTAL
FROM		PET..CUSTOMER C FULL JOIN PET..SALE S ON C.CUSTOMERID = S.CUSTOMERID
			FULL JOIN PET..SALEITEM SI ON S.SALEID = SI.SALEID
			FULL JOIN PET..SALEANIMAL SA ON S.SALEID = SA.SALEID
GROUP BY	C.CUSTOMERID, C.LASTNAME, C.FIRSTNAME 
ORDER BY	SUM(SI.SALEPRICE*SI.QUANTITY)+SUM(SA.SALEID) DESC 



--6
SELECT		C.CUSTOMERID, C.LASTNAME, C.FIRSTNAME, TABLE1.SALEPRICE AS 'MAYTOTAL'
FROM		PET..CUSTOMER C JOIN 
				(SELECT S.CUSTOMERID, SI.SALEPRICE FROM PET..SALE S JOIN PET..SALEITEM SI ON S.SALEID = SI.SALEID
				WHERE SI.SALEPRICE > 100 AND (S.SALEDATE BETWEEN '2004-05-01' AND '2004-05-31')) TABLE1 
				ON C.CUSTOMERID = TABLE1.CUSTOMERID
				JOIN 
				(SELECT S.SALEID, SI.SALEPRICE, S.SALEDATE, S.CUSTOMERID FROM PET..SALE S JOIN PET..SALEITEM SI ON S.SALEID = SI.SALEID
				WHERE SI.SALEPRICE > 50 AND (S.SALEDATE BETWEEN '2004-10-01' AND '2004-10-30')) TABLE2 
				ON TABLE1.CUSTOMERID = TABLE2.CUSTOMERID

--7
SELECT		DESCRIPTION, M.ITEMID, SUM(OI.QUANTITY) PURSHCASED, SUM(SI.QUANTITY) SOLD, SUM(OI.QUANTITY) - SUM(SI.QUANTITY) AS NETINCREASE
FROM		PET..MERCHANDISE M JOIN PET..ORDERITEM OI ON M.ITEMID = OI.ITEMID 
			JOIN PET..SALEITEM SI ON M.ITEMID = SI.ITEMID 
			JOIN PET..MERCHANDISEORDER MO ON MO.PONUMBER = OI.PONUMBER 
WHERE		DESCRIPTION = 'Dog Food-Can-Premium' AND MO.ORDERDATE BETWEEN '2004-01-01' AND '2004-07-30'
GROUP BY	DESCRIPTION, M.ITEMID

--8
SELECT		TABLE1.ITEMID, M.DESCRIPTION, M.LISTPRICE, TABLE1.SALEDATE
FROM		PET..MERCHANDISE M JOIN
			(SELECT SI.ITEMID, S.SALEDATE, SI.SALEID FROM PET..SALE S JOIN PET..SALEITEM SI ON S.SALEID = SI.SALEID
			WHERE SI.ITEMID NOT IN (SELECT SI.ITEMID FROM PET..SALE S JOIN PET..SALEITEM SI ON S.SALEID = SI.SALEID  WHERE S.SALEDATE BETWEEN '2004-07-01' AND '2004-07-30')) TABLE1 
			ON M.ITEMID = TABLE1.ITEMID WHERE M.LISTPRICE > 50 

--9
SELECT		M.ITEMID, M.DESCRIPTION, M.QUANTITYONHAND, M.ITEMID
FROM		PET..MERCHANDISE M LEFT JOIN PET..ORDERITEM OI ON M.ITEMID = OI.ITEMID 
			LEFT JOIN PET..MERCHANDISEORDER MO ON OI.PONUMBER = MO.PONUMBER 
WHERE		MO.ORDERDATE IS NULL AND M.QUANTITYONHAND > 100

--10
SELECT		M.ITEMID, M.DESCRIPTION, M.QUANTITYONHAND, M.ITEMID
FROM		PET..MERCHANDISE M
WHERE		M.QUANTITYONHAND > 100 AND M.ITEMID NOT IN (SELECT OI.ITEMID FROM PET..ORDERITEM OI) 

--11----
CREATE TABLE PET..CETEGORY_NEW( 
CUSTOMERID		INT NOT NULL,
C_N				VARCHAR(35), 
LOW_C			INT,	
HIGH_C			INT)

SELECT		TOP 1 C.CUSTOMERID, C.LASTNAME, C.FIRSTNAME, SUM(SI.SALEPRICE*SI.QUANTITY) MERCTOTAL, SUM(SA.SALEID) ANIMALTOTAL, SUM(SI.SALEPRICE*SI.QUANTITY)+SUM(SA.SALEID) GRANDTOTAL
FROM		PET..CUSTOMER C FULL JOIN PET..SALE S ON C.CUSTOMERID = S.CUSTOMERID
			FULL JOIN PET..SALEITEM SI ON S.SALEID = SI.SALEID
			FULL JOIN PET..SALEANIMAL SA ON S.SALEID = SA.SALEID
GROUP BY	C.CUSTOMERID, C.LASTNAME, C.FIRSTNAME 
ORDER BY	SUM(SI.SALEPRICE*SI.QUANTITY)+SUM(SA.SALEID) DESC 


--12
SELECT		S.NAME AS 'SUPPLIER NAME', 'ANIMALS' AS 'ORDER TYPE'
FROM		PET..SUPPLIER S JOIN PET..ANIMALORDER AO ON S.SUPPLIERID = AO.SUPPLIERID 
UNION 
SELECT		S.NAME AS 'SUPPLIER NAME', 'MERCHANDISE' AS 'ORDER TYPE'
FROM		PET..SUPPLIER S JOIN PET..MERCHANDISEORDER MO ON S.SUPPLIERID = MO.SUPPLIERID 








